### ISSUE TITLE
Telnet Problem

### ISSUE THREAD

**Issue by Nailik** [CABrouwers/node-red-contrib-synaccess-netbooter#3]
I'm sorry that i open an issue here on the wrong package but i couldn't find any contact information.

I tried to use your Node Red Telnet Client Package https://flows.nodered.org/node/node-red-contrib-telnet-client 
but i got some Problems.

The nodes are broken.

![df](https://user-images.githubusercontent.com/13292441/98223056-e2093b80-1f51-11eb-8c61-cf1a589927e0.JPG)

First i had V 1.0.0 and the connection node was like this and some minutes later randomly it changed to V 1.0.1 (it says updated 2 months ago but i swear there was V 1.0.0 yesterday).

**Comment by CABrouwers** [comment]
Thanks for bringing up the issue.  Unfortunately, I can't reproduce it and the sudden change of version you experienced is also mysterious. Version 1.0.1 was uploadled months ago. Just in case, i have updated the version number of a critical dependency (openpromise), I am thinking there might have been an issue with the older verion. Test now node-red-contrib-telnet client version 1.0.3 , it will pull the most recent version of openpromise and should work. Also, i have now created a github repository for the source code. Please post futher commetns or issue there. Thanks

**Comment by Nailik** [comment]
Thank you for the fast reply.
Maybe it's because i use NodeRed as Docker Container, plugin from Home Assitant.
The way i tried to solve the problems is here: https://discourse.nodered.org/t/telnet-connection-node-missing-after-install/35329/14
There is still V 1.0.1 here https://flows.nodered.org/node/node-red-contrib-telnet-client.

Could you create a build tgz file so i can install it manually?

**Comment by CABrouwers** [comment]
give it an hour for node-red to pull version 1.0.3 out from NPM where it is already uploaded. Alternatively, you can get it directly from NPM or create a build from the source code on Github where it is now posted. I will track the availability on node-red and test the new version when it becomes available.

**Comment by CABrouwers** [comment]
Also, the node is based on my module https://github.com/CABrouwers/telnet-engine; read the MD file to see how the node works.

**Comment by Nailik** [comment]
Do you have any idea why the package is not shown as installed in the ui when i install it with the terminal?

After updating to 1.0.3 problem remains the same.

**Comment by Nailik** [comment]
@CABrouwers I found the reason for the version jump, i clicked on **Request Refresh** in Node-Red Library - because without it didn't update.
Should be fixed now by [https://github.com/CABrouwers/node-red-contrib-telnet/issues/1](https://github.com/CABrouwers/node-red-contrib-telnet/issues/1)
